environment:
  name: "idsgame-random-attack-v20"
  parameters:
    render: false  
    seed: 42      

sarsa:
  # Learning parameters
  learning_rate: 0.1
  gamma: 0.99  
  epsilon:
    start: 1.0
    end: 0.01
    decay: 0.995

  # Training parameters
  training:
    num_episodes: 1000
    max_steps_per_episode: 100
    evaluation:
      frequency: 100  
      episodes: 10    
    
  # Logging and metrics
  logging:
    frequency: 10   
    metrics:
      - "episode_reward"
      - "episode_length"
      - "epsilon"
      - "attack_success_rate"
      - "defense_success_rate"
    
  # Model checkpointing
  checkpoint:
    frequency: 100  
    dir: "models/sarsa"

  # Memory settings
  memory:
    size: 10000
    batch_size: 32

ddqn:
  # Neural Network parameters
  network:
    architecture:
      - 128  
      - 64  
    activation: "relu"
    learning_rate: 0.001
    optimizer: "adam"
    loss: "mse"
    
  # Training parameters
  training:
    num_episodes: 1000
    max_steps_per_episode: 100
    target_update_frequency: 100  
    evaluation:
      frequency: 100
      episodes: 10
      
  # Exploration parameters
  epsilon:
    start: 1.0
    end: 0.01
    decay: 0.995
    
  # Experience replay
  memory:
    size: 100000
    batch_size: 64
    
  # Logging and checkpoints
  logging:
    frequency: 10
    metrics:
      - "episode_reward"
      - "episode_length"
      - "epsilon"
      - "loss"
      - "attack_success_rate"
      
  checkpoint:
    frequency: 100
    dir: "models/ddqn"

# General logging settings
logging:
  level: "INFO"
  dir: "logs"
  filename: "training.log"
  console_output: true
  save_to_file: true
  
# Visualization settings
visualization:
  show_training_progress: true
  save_plots: true
  plots_dir: "plots"
  metrics_to_plot:
    - "episode_reward"
    - "episode_length"
    - "epsilon"